### PR TITLE
Add support for !include example.json

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Comment by mcheguini** [comment]
Hi @StefH, I checked and example "!include somejsonfile.json" , it is working (: ,  can you please merge it with master branch.
When you have a time please take a quick look at #12 ,  
I really appreciate it.

**Comment by mcheguini** [comment]
@StefH , issue with "example !include somejsonfile.json" already solved.
The issue is "!inlcude someraml.raml" is not working any longer! (it was working before this commit)
```
#%RAML 1.0
title: include array example
description: this is a description of array example file
protocols:
  - HTTP
version: 1.0
mediaType:
  - application/json

types:
  Email: !include datatypes/email.raml
  Emails: !include datatypes/emails.raml

/arraytest2:
  get:
    description: this is an example array response
    responses:
      200:
        body:
          application/json:
            type: Emails

```

**Comment by StefH** [comment]
0.4.3 should fix this issue

**Comment by mcheguini** [comment]
Thanks @StefH you are a genius (:

**Pull request merged**
